export const LAY_DANH_SACH_NGUOI_DUNG = "LAY_DANH_SACH_NGUOI_DUNG";

export const LAY_DS_NGUOI_DUNG_RENDER = "LAY_DS_NGUOI_DUNG_RENDER";

export const XOA_NGUOI_DUNG = "XOA_NGUOI_DUNG";

export const SEARCH_USER = "SEARCH_USER";
export const LAY_DS_KH_CHUA_XET_DUYET = "LAY_DS_KH_CHUA_XET_DUYET";
export const LAY_DS_KH_DA_XET_DUYET = "LAY_DS_KH_DA_XET_DUYET";
export const LAY_DS_KH_CHO_XET_DUYET = "LAY_DS_KH_CHO_XET_DUYET";
export const LAY_DS_HV_CHO_XET_DUYET = "LAY_DS_HV_CHO_XET_DUYET";
export const LAY_DS_HV_KHOA_HOC = "LAY_DS_HV_KHOA_HOC";
