export const LAY_DANH_MUC_KHOA_HOC = "LAY_DANH_MUC_KHOA_HOC";
export const LAY_DANH_SACH = "LAY_DANH_SACH";
export const LAY_CHI_TIET_KHOA_HOC = "LAY_CHI_TIET_KHOA_HOC";
export const LAY_KHOA_HOC_THEO_MUC = "LAY_KHOA_HOC_THEO_MUC";
export const LAY_KHOA_HOC_THEO_SEARCH = "LAY_KHOA_HOC_THEO_SEARCH";
export const LAY_KHOA_HOC_THEO_NGUOI_DUNG = "LAY_KHOA_HOC_THEO_NGUOI_DUNG";
